version: '3'

services: 

  laravel:
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    image: rafael/express:prod
    container_name: laravel
    networks: 
      - laranet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: rafael/nginx:prod
    container_name: nginx
    networks: 
      - laranet
    ports: 
      - "8080:80"
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  laranet:
    driver: bridge  